apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: random-server
  template:
    metadata:
      labels:
        app: random-server
    spec:
      containers:
        - name: random-server
          image: vesk18/random-server:latest
          ports:
            - containerPort: 8082
