apiVersion: v1
kind: Service
metadata:
  name: random-server-service
spec:
  type: NodePort
  selector:
    app: random-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
      nodePort: 30082
