---
- name: Setup Jenkins and nginx on master
  hosts: ec2-master
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Java 11
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Add Jenkins apt key (new method)
      shell: |
        curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee \
          /usr/share/keyrings/jenkins-keyring.asc > /dev/null
      args:
        executable: /bin/bash

    - name: Add Jenkins repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        state: present
        filename: jenkins

    - name: Update apt again after adding Jenkins repo
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Configure Nginx for Jenkins reverse proxy
      template:
        src: nginx_jenkins.conf.j2
        dest: /etc/nginx/sites-available/jenkins.conf
      notify:
        - Enable jenkins site
        - Restart nginx

    - name: Enable jenkins site and disable default
      file:
        src: /etc/nginx/sites-available/jenkins.conf
        dest: /etc/nginx/sites-enabled/jenkins.conf
        state: link
      notify:
        - Restart nginx

    - name: Remove default nginx site if exists
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify:
        - Restart nginx

    - name: Start and enable Jenkins
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Start and enable nginx
      service:
        name: nginx
        state: started
        enabled: yes

  handlers:
    - name: Enable jenkins site
      command: ln -sf /etc/nginx/sites-available/jenkins.conf /etc/nginx/sites-enabled/jenkins.conf

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
